// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pba_api.Data;

#nullable disable

namespace pba_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221116083702_AddSeveralModels")]
    partial class AddSeveralModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pba_api.Models.AdditionalExpensesModel.AdditionalExpense", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Continuous")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EstimateSheetId")
                        .HasColumnType("int");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("AdditionalExpenses");
                });

            modelBuilder.Entity("pba_api.Models.CustomerModel.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("pba_api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("pba_api.Models.EpicModel.Epic", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("EpicName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EpicStatusId")
                        .HasColumnType("int");

                    b.Property<int>("EstimateSheetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EpicStatusId");

                    b.ToTable("Epics");
                });

            modelBuilder.Entity("pba_api.Models.EpicStatusModel.EpicStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EpicStatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EpicStatuses");
                });

            modelBuilder.Entity("pba_api.Models.EstimateSheetModel.EstimateSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("JiraBoardId")
                        .HasColumnType("int");

                    b.Property<string>("JiraLink")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("SheetStatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WireframeLink")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("WorkbookLink")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SheetStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("EstimateSheets");
                });

            modelBuilder.Entity("pba_api.Models.SheetStatusModel.SheetStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SheetStausName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SheetStatuses");
                });

            modelBuilder.Entity("pba_api.Models.UserModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2400)
                        .HasColumnType("varchar(2400)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pba_api.Models.AdditionalExpensesModel.AdditionalExpense", b =>
                {
                    b.HasOne("pba_api.Models.EstimateSheetModel.EstimateSheet", "EstimateSheet")
                        .WithMany("AdditionalExpenses")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstimateSheet");
                });

            modelBuilder.Entity("pba_api.Models.EpicModel.Epic", b =>
                {
                    b.HasOne("pba_api.Models.EpicStatusModel.EpicStatus", "EpicStatus")
                        .WithMany("Epics")
                        .HasForeignKey("EpicStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pba_api.Models.EstimateSheetModel.EstimateSheet", "EstimateSheet")
                        .WithMany("Epics")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EpicStatus");

                    b.Navigation("EstimateSheet");
                });

            modelBuilder.Entity("pba_api.Models.EstimateSheetModel.EstimateSheet", b =>
                {
                    b.HasOne("pba_api.Models.CustomerModel.Customer", "Customer")
                        .WithMany("EstimateSheets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pba_api.Models.SheetStatusModel.SheetStatus", "SheetStatus")
                        .WithMany("EstimateSheets")
                        .HasForeignKey("SheetStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pba_api.Models.UserModel.User", "User")
                        .WithMany("EstimateSheets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SheetStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("pba_api.Models.CustomerModel.Customer", b =>
                {
                    b.Navigation("EstimateSheets");
                });

            modelBuilder.Entity("pba_api.Models.EpicStatusModel.EpicStatus", b =>
                {
                    b.Navigation("Epics");
                });

            modelBuilder.Entity("pba_api.Models.EstimateSheetModel.EstimateSheet", b =>
                {
                    b.Navigation("AdditionalExpenses");

                    b.Navigation("Epics");
                });

            modelBuilder.Entity("pba_api.Models.SheetStatusModel.SheetStatus", b =>
                {
                    b.Navigation("EstimateSheets");
                });

            modelBuilder.Entity("pba_api.Models.UserModel.User", b =>
                {
                    b.Navigation("EstimateSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
